### PR TITLE
Added new article and notebook

### PR DESCRIPTION
**Pull request by Lplenka**
Added one new article and a new section for Jupyter Notebooks

### CODE REVIEW

**Comment by arnas** [comment]
Hey, thank you for contribution. Please also add category link to jupiter notebook

**Comment by arnas** [comment]
@Lplenka Have you checked if it autoscrolls when clicked to the section? 
Not sure if `-` will work. You might have to add `&#32;` instead of space

**Comment by Lplenka** [comment]
@arnas yes works :+1:

**Comment by arnas** [comment]
Nice

**Pull request merged**
